# Generated by Django 2.0.3 on 2018-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_image',
            field=models.CharField(max_length=1024),
        ),
    ]
